version: '3'

services:
  static_web_server:
    build: staticWebServer
    expose:
      - "80"
    volumes:
      - ./staticWebServer/config/log:/var/log/nginx
    labels:
      # Explicitly tell traefik to expose this container.
      - "traefik.enable=true"
      # Defines the domain to which the service responds.
      - "traefik.http.routers.staticWeb-router.rule=Host(`localhost`)"
      # Routes all requests to the service static-router.
      - "traefik.http.routers.staticWeb-router.service=staticWeb-service"
      # Defines the port on which the service responds.
      - "traefik.http.services.staticWeb-service.loadbalancer.server.port=80"
    deploy:
      replicas: 2
  api_server:
    build: api_server
    expose:
      - "80"
    labels:
      # Explicitly tell traefik to expose this container.
      - "traefik.enable=true"
      # Defines the path-prefixed domain to which the service responds.
      - "traefik.http.routers.api-router.rule=Host(`localhost`) && PathPrefix(`/api`)"
      # Routes all requests to the service api-router.
      - "traefik.http.routers.api-router.service=api-service"
      # Enables the sticky session for the api-service.
      - "traefik.http.services.api-service.loadbalancer.sticky=true"
      # Sets the cookie name to identify the session.
      - "traefik.http.services.api-service.loadbalancer.sticky.cookie.name=apicookie"
      # Defines the port on which the service responds.
      - "traefik.http.services.api-service.loadbalancer.server.port=80"
    deploy:
      replicas: 3
  reverse_proxy:
    container_name: reverse_proxy
    image: traefik
    command:
      # Enables the web UI and tells Traefik to listen to docker
      - "--api.insecure=true"
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      # Enables access logs
      - "--accesslog=true"
      - "--accesslog.filePath=/var/log/traefik/access.log"
      - "--accesslog.fields.names.StartUTC=drop"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    environment:
      - TZ=Europe/Zurich
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Mounts a local volume to have access to the logs.
      - ./reverse_proxy/log:/var/log/traefik/